services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  backend:
    build: ./backend
    container_name: django
    command: ./entrypoint.sh
    volumes:
      - ./backend:/app
      - ${HOST_PROJECT_PATH}:${HOST_PROJECT_PATH}
    network_mode: host
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  frontend:
    build: ./frontend
    container_name: vite
    network_mode: host
    env_file:
      - .env
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 64M

volumes:
  postgres_data: