# Generated by Django 6.0.2 on 2026-03-04 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], max_length=10)),
                ('external_id', models.CharField(max_length=64)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('brand', models.CharField(blank=True, max_length=256)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('delivery_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url', models.URLField(max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'marketplace', 'external_id')},
            },
        ),
    ]
