# Generated by Django 6.0.2 on 2026-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproduct',
            name='marketplace',
            field=models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon')], max_length=11),
        ),
    ]
